engines:
  duplication:
    enabled: false
  fixme:
    enabled: true
  radon:
    enabled: true
    threshold: "C"
  pep8:
    enabled: true
ratings:
  paths:
  - "**.py"
exclude_paths:
  - src/kpop/tests/